// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8SJsq73H6xgW3wn3I9Dth8lXqVs4_Qf0',
    appId: '1:985597276695:web:cf30332cf0478cf091e252',
    messagingSenderId: '985597276695',
    projectId: 'binmart',
    authDomain: 'binmart.firebaseapp.com',
    storageBucket: 'binmart.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: "AIzaSyDkCUYBRpfwtKY5OH9zFjKPgCeKFAizRpg",
    appId: '1:985597276695:android:c212d1a8339a851991e252',
    messagingSenderId: '985597276695',
    projectId: 'binmart',
    storageBucket: 'binmart.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAL9-YnriyXEX7iiZqASnP0Ue5WBqpl17U',
    appId: '1:985597276695:ios:cefd706f480491b491e252',
    messagingSenderId: '985597276695',
    projectId: 'binmart',
    storageBucket: 'binmart.firebasestorage.app',
    iosBundleId: 'com.example.binmart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAL9-YnriyXEX7iiZqASnP0Ue5WBqpl17U',
    appId: '1:985597276695:ios:cefd706f480491b491e252',
    messagingSenderId: '985597276695',
    projectId: 'binmart',
    storageBucket: 'binmart.firebasestorage.app',
    iosBundleId: 'com.example.binmart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8SJsq73H6xgW3wn3I9Dth8lXqVs4_Qf0',
    appId: '1:985597276695:web:2c90fff848c6d6a191e252',
    messagingSenderId: '985597276695',
    projectId: 'binmart',
    authDomain: 'binmart.firebaseapp.com',
    storageBucket: 'binmart.firebasestorage.app',
  );
}
